name: Pilltracker1
favicon: null
layout_spectrum: 0.2425
typography_spectrum: 0.50453
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#72ac54'
    - '#eeaa13'
    - '#ff00ff'
    - '#000000'
    - '#0000ff'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 1
purpose: []
